use_frameworks!

platform :ios, '8.0'

target 'OneDemoSDK_Example' do
  pod 'OneDemoSDK', :path => '../'

  target 'OneDemoSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
